server:
  port: 8080
  servlet:
    context-path: /ameya
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/usermanagement
    username: root
    password: 7132000@23
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
  redis:
    host: localhost
    port: 6379
    hashKey: usermanagement
resilience4j:
  ratelimiter:
    default:
      limit-for-period: 10
      limit-refresh-period: 1s
      limit-for-burst: 5
    instances:
      createUserRateLimiter:
        baseConfig: default
      getUserRateLimiter:
        baseConfig: default
      updateUserRateLimiter:
        baseConfig: default
      deleteUserRateLimiter:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
    instances:
      createUserRetry:
        baseConfig: default
      getUserRetry:
        baseConfig: default
management:
  endpoints:
    web:
      exposure:
        include: "*"

  logging:
    level:
      ROOT: INFO
      org.springframework.orm.jpa: DEBUG
      org.springframework.transaction: DEBUG
